format = """$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$container\
$cmd_duration\
$fill\
$nodejs\
$golang\
$python\
$time\
$line_break\
$character
"""

add_newline = false

[fill]
symbol = ' '
style = 'bold green'

[directory]
style = "blue"

[time]
disabled = false
style="black"
format = '[ $time ]($style) '
time_format = '%T'
utc_time_offset = 'local'

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[$branch]($style) "
style = "bright-black"

[git_status]
style = "black"
# format = "[[(*$conflicted$count$modified$count$untracked$count$staged$count$renamed$count$deleted$count)](218) ($ahead_behind$stashed)]($style)"
format = '([$all_status$ahead_behind]($style) )'
conflicted = "=${count}"
untracked = "?${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "x${count}"
stashed = "≡${count}"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "bright-black"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[nodejs]
format = '[$symbol$version](bold black) '

[golang]
symbol = " "
format = '[$symbol$version](bold black) '

[container]
format = '[$symbol \[$name\]]($style) '
