set-option -g default-shell /bin/zsh
set-option -sa terminal-overrides ",alacritty:RGB"
set-option -sg escape-time 10
set-option -g focus-events on
set -g visual-activity off
set -g visual-bell off
set -g mouse on
# For pi
set -g extended-keys on
set -g extended-keys-format csi-u

# Change prefix to Ctrl - b which is mapped to alt - e in skhd
set-option -g prefix C-b
bind-key C-b send-prefix

setw -g mode-keys vi

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
# Vim-like copy-mode behavior
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi C-v send -X rectangle-toggle
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel
bind-key -T copy-mode-vi Escape send -X cancel
bind-key -T copy-mode-vi q send -X cancel

# More natural scrolling in copy mode
bind-key -T copy-mode-vi C-u send -X halfpage-up
bind-key -T copy-mode-vi C-d send -X halfpage-down
bind-key -T copy-mode-vi C-b send -X page-up
bind-key -T copy-mode-vi C-f send -X page-down
bind-key -T copy-mode-vi g send -X history-top
bind-key -T copy-mode-vi G send -X history-bottom

# Search like Vim
bind-key -T copy-mode-vi / command-prompt -i -p "search down" "send -X search-forward-incremental '%%'"
bind-key -T copy-mode-vi ? command-prompt -i -p "search up" "send -X search-backward-incremental '%%'"
bind-key -T copy-mode-vi n send -X search-again
bind-key -T copy-mode-vi N send -X search-reverse

# Open panes
bind l split-window -h -c "#{pane_current_path}"  
bind j split-window -v -c "#{pane_current_path}"  
bind h split-window -h -b -c "#{pane_current_path}"   
bind k split-window -v -b -c "#{pane_current_path}"   

# Sessions
# Alt - q/w to cycle sessions
bind-key -n M-q switch-client -p
bind-key -n M-w switch-client -n
bind-key -n M-z switch-client -l

# Alt - u/i to cycle windows
bind-key -n M-u previous-window
bind-key -n M-i next-window
bind-key -n M-y last-window

bind-key -n C-e display-popup -E -w 80% -h 70% -d '#{pane_current_path}' -T 'Sesh' "zsh -f -c '~/.local/bin/tmux-sesh'"
bind-key s display-popup -E -w 80% -h 70% -d '#{pane_current_path}' -T 'Sessions' "zsh -f -c '~/.local/bin/tmux-open-sessions'"

# New tmux window, no prefix
bind-key -n M-Enter new-window -c "#{pane_current_path}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'pschmitt/tmux-ssh-split'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
# set -g @plugin 'omerxx/tmux-sessionx'
# set -g @sessionx-bind 's'

# tmux ssh
set -g @ssh-split-keep-cwd "true"
set -g @ssh-split-keep-remote-cwd "true"
set -g @ssh-split-w-key "C"

# Disable bindings
bind -n C-g
bind -n C-f

bind-key s display-popup -E -w 80% -h 70% -d '#{pane_current_path}' -T 'Sessions' "zsh -f -c '~/.local/bin/tmux-open-sessions'"

# LLM AGENT POPUP
bind-key C-e display-popup -w 45% -h 35% -x 5000 -y 0 -E "tmux new-session -A -s pi-agent 'zsh -ic pi'"
bind r split-window -h -c "#{pane_current_path}" "/Users/phil/.local/share/mise/installs/node/26/bin/pi -c; exec zsh"

# Catppuccin
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_current_number_color "#{@thm_blue}"
set -g status-left ""
set -g status-right-length 100
set -g status-left-length 100
set -ag status-right "#{E:@catppuccin_status_session}"
set -g @catppuccin_session_text "#[bold] #S#[nobold]"
set -g @catppuccin_status_left_separator ""
set -g @catppuccin_status_middle_separator ""
set -g @catppuccin_status_right_separator " "
set -g @catppuccin_session_icon ""
# Popup styles
set -g popup-style bg='#1e1e2e'
set -g popup-border-lines rounded
set -g popup-border-style fg=black

run '~/.config/tmux/plugins/tpm/tpm'
